# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-28 07:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='img_url',
        ),
        migrations.AddField(
            model_name='location',
            name='img',
            field=models.ImageField(default='location_images/default.png', upload_to='location_images'),
        ),
        migrations.AddField(
            model_name='location',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
